version: "3.9"
services:
  shop-db:
    image: postgres:16
    container_name: shop-db-postgres
    restart: always
    ports:
      - "5333:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: mydb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  shop-api:
    build: ./onlineshop
    container_name: shop-api
    ports:
      - "8000:8000"
    depends_on:
        - shop-db
        - minio
    command: >
      sh -c "python wait_for_services.py &&
             python manage.py runserver 0.0.0.0:8000"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  minio_data:

